const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const EDIT_TODO = "EDIT_TODO";
const MARK_TODO = "MARK_TODO";
const MARK_ALL = "MARK_ALL";
const CLEAR_MARK = "CLEAR_MARK";
const FETCH_DATA_BEGIN = "FETCH_DATA_BEGIN";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

export {
  ADD_TODO,
  DELETE_TODO,
  EDIT_TODO,
  MARK_TODO,
  MARK_ALL,
  CLEAR_MARK,
  FETCH_DATA_BEGIN,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAIL
};
