const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const MARK_TODO = 'MARK_TODO';
const MARK_ALL = 'MARK_ALL';
const CLEAR_MARK = 'CLEAR_MARK';

export {ADD_TODO, DELETE_TODO, EDIT_TODO, MARK_TODO, MARK_ALL, CLEAR_MARK}